# Generated by Django 3.2 on 2021-04-10 17:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HFControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', ckeditor.fields.RichTextField()),
                ('fb_link', models.CharField(max_length=50)),
                ('insta_link', models.CharField(max_length=50)),
                ('tweeter_link', models.CharField(max_length=50)),
                ('youtube_link', models.CharField(max_length=50)),
            ],
        ),
    ]
