# Generated by Django 3.2 on 2021-04-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='emails',
            new_name='email',
        ),
    ]
