# Generated by Django 3.2 on 2021-04-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_alter_youtuber_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='is_features',
            new_name='is_featured',
        ),
    ]
