# Generated by Django 3.2 on 2021-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_rename_is_features_youtuber_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='photo',
            field=models.ImageField(upload_to='media/ytubers/%Y/%m/'),
        ),
    ]
