# Generated by Django 3.2 on 2021-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0002_auto_20210410_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='tuber_price',
            field=models.CharField(max_length=255),
        ),
    ]
